### ISSUE TITLE
阿里云部署失败

### ISSUE THREAD

**Issue by adai521** [LittleControl/AutoNeteaseMusic#3]
依赖无法安
![QQ图片20220530111852](https://user-images.githubusercontent.com/68664583/170911111-bcad09f1-90eb-491d-9eb4-11aceda5eb8f.png)
![QQ图片20220530111916](https://user-images.githubusercontent.com/68664583/170911113-edadd9b7-934f-4ba1-95a7-ebf77b811210.png)
装

**Comment by KnowSky404** [comment]
导入包后在代码根目录下执行一下 npm install即可
