### ISSUE TITLE
希望能加一个bool，开关是否进行歌曲打卡

### ISSUE THREAD

**Issue by owwkmidream** [LittleControl/AutoNeteaseMusic#5]
适用于多账号，有些仅需要签到。

**Comment by owwkmidream** [comment]
恶补了下js语法，解决了。
想问问作者index.js是用什么生成的吗，看起来像是app.js转的

**Comment by KnowSky404** [comment]
> 适用于多账号，有些仅需要签到。

好注意,后面应该要加入这个功能

**Comment by KnowSky404** [comment]
> 恶补了下js语法，解决了。 想问问作者index.js是用什么生成的吗，看起来像是app.js转的

app.js是源文件,然后index.js是用babel打包生成的
具体命令可参考package.json里的build命令

**Comment by owwkmidream** [comment]
> > 恶补了下js语法，解决了。 想问问作者index.js是用什么生成的吗，看起来像是app.js转的
> 
> app.js是源文件,然后index.js是用babel打包生成的 具体命令可参考package.json里的build命令

感谢，已提交PR
